services:
  # ----------------------------------------------------
  # 服務一：web-1 (內部端口 9999, Host: web1.local)
  # ----------------------------------------------------
  web-1:
    image: traefik/whoami # 使用 Traefik 官方測試鏡像，默認監聽 80 端口。
    container_name: web-1
    # 由於 whoami 默認監聽 80，為了模擬您的 9999 需求，我們需要傳入參數
    command: ["--port", "9999"]

    labels:
      - traefik.enable=true
      # Router for web-1
      - traefik.http.routers.web-1-router.entrypoints=custom_port
      - traefik.http.routers.web-1-router.rule=Host(`web1.local`)
      # Service for web-1: **重點在這裡！** 指定容器內部監聽的 9999 端口
      - traefik.http.services.web-1-service.loadbalancer.server.port=9999

    networks:
      - webproxy # 只連接到這個單一的網路

  # ----------------------------------------------------
  # 服務二：web-2 (內部端口 10000, Host: web2.local)
  # ----------------------------------------------------
  web-2:
    image: traefik/whoami
    container_name: web-2
    # 為了模擬您的 10000 需求，我們傳入參數
    command: ["--port", "10000"]

    labels:
      - traefik.enable=true
      # Router for web-2
      - traefik.http.routers.web-2-router.entrypoints=web
      - traefik.http.routers.web-2-router.rule=Host(`web2.local`)
      # Service for web-2: **重點在這裡！** 指定容器內部監聽的 10000 端口
      - traefik.http.services.web-2-service.loadbalancer.server.port=10000

    networks:
      - webproxy # 只連接到這個單一的網路

networks:
  webproxy:
    external: true